# Generated by Django 5.1.6 on 2025-03-02 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_recurringexpense'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecurringExpense',
        ),
    ]
